api_platform:
    title: "CRM Projectil-Sogrepress"
    description: "Outil de gestion commeriale pour l'entreprise Projectil-Sogepress"
    version: "1.0.0"
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    show_webby: false
